[env]
TERM = "xterm-256color"

[font]
size = 13.0

[font.bold]
family = "Menlo"
style = "Bold"

[font.bold_italic]
family = "Menlo"
style = "Bold Italic"

[font.italic]
family = "Menlo"
style = "Italic"

[font.normal]
family = "Menlo"
style = "Regular"

[window]
decorations = "buttonless"
opacity = 0.8

[window.padding]
x = 10
y = 10

